### PR TITLE
WavParse Testing and fixes

### PR DESCRIPTION
**Pull request by robbiet480**
#11 must be merged first!

### CODE REVIEW

**Comment by robbiet480** [comment]
@rabarar FYI this was a draft PR (last I checked at least). Draft PRs usually shouldn’t be merged before the author marks them as ready. I still had work left to do on this. NBD though, will just make a new PR in a bit.

**Comment by rabarar** [comment]
Sounds good - i saw that but wasn’t sure - noted for next time. So in general, the workflow for a draft is to let it stew until it’s no longer draft and then approve/merge it?

**Comment by robbiet480** [comment]
@rabarar Pretty much. Only reason I opened this PR now was because I had Github Actions I was testing in the PR which can only be done on Github itself. Normally I wait to open until its ready to merge.

**Comment by rabarar** [comment]
Cool. Makes sense.

**Pull request merged**
