### PR TITLE
SDS100 audio

### PR DESCRIPTION
**Pull request by robbiet480**
- Adds support for Audio Feed which will automatically copy audio files over as they are created on the scanner.
- Adds a Uniden WAV file parser. Partially reverse engineered. It's a wealth of data!

#6

### CODE REVIEW

**Comment by robbiet480** [comment]
@rabarar Do me a favor and take a close look at this and also let me know if it works on your SDS200! It's safe to ignore the `Scanner said last command was invalid during file transfer` warnings for now, not sure where they are coming from and I think it's just a timing issue.

**Comment by robbiet480** [comment]
Noticed that the private metadata heuristics break on non-trunked systems. Will fix tomorrow but I don't think we should hold up merging this because of that.

**Comment by robbiet480** [comment]
Did this work on your SDS200?

**Comment by rabarar** [comment]
what do you mean by “this”?

**Comment by robbiet480** [comment]
I mean when you started up the server did it successfully start downloading audio files from your SDS200?

**Comment by rabarar** [comment]
nope. And using the  websocat -t - autoreconnect:ws://localhost:8080 <ws://localhost:8080/> doesn’t connect to the bearcatter and respond either.

**Comment by rabarar** [comment]
I verified there are two recordings on the scanner: here’s the output when I start up the server (while it’s connected via USB)

$ ./bearcatter -u /dev/tty.usbmodem142401  -r ./audio
INFO[0000] Connected to /dev/tty.usbmodem142401 via USB 
INFO[0000] Started WebSocket Server at :8080            
WARN[0001] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0001] success true                                 
INFO[0001] Scanner -> Host AUF	STS	NG	646               
WARN[0001] Received a HomePatrol message!               
WARN[0001] Scanner said last command was invalid during file transfer 
WARN[0002] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0002] Scanner -> Host AUF	INFO	NG	696              
WARN[0002] Received a HomePatrol message!               
WARN[0002] Scanner said last command was invalid during file transfer 
WARN[0003] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0003] Scanner -> Host AUF	INFO	NG	696              
WARN[0003] Received a HomePatrol message!               
WARN[0003] Scanner said last command was invalid during file transfer 
WARN[0004] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0004] Scanner -> Host AUF	INFO	NG	696              
WARN[0004] Received a HomePatrol message!               
WARN[0004] Scanner said last command was invalid during file transfer 
WARN[0005] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0005] Scanner -> Host AUF	INFO	NG	696              
WARN[0005] Received a HomePatrol message!               
WARN[0005] Scanner said last command was invalid during file transfer 
^CINFO[0005] Terminating on signal...                     
WARN[0005] HostMsgChannel: No Listener to Receive Msg, Msg Not Sent 
INFO[0005] Shutting down WebSocket server               
INFO[0005] Shutting down file polling                   
INFO[0005] UDPServer Terminated.

**Comment by robbiet480** [comment]
Would be interesting to have you connect manually to the UDP port and run the commands to start up the Audio Feed function. If you check utils.go you can just use the HomePatrol command function. You want to run these commands (these are all `[]string{}`):

```
“AUF”, “STS” // returns ON/OFF for audio feed status
“AUF”, “STS”, “ON” // turn on audio feed
// wait for a audio transmission to complete
“AUF”, “INFO” // should show file name and size
“AUF”, “INFO”, “ACK” // ack that you have received file data
“AUF”, “DATA” // you’ll receive a data blob
“AUF”, “DATA”, “CAN” // cancel the data transfer
```

**Comment by rabarar** [comment]
AUF,STS  in the UDP port returns error. Connecting via USB reports the same error. No such command in the SDS200…

**Comment by rabarar** [comment]
are you sending a checksum as well with these commands as indicated in the docs? or just “AUF,STS\r”

**Comment by robbiet480** [comment]
Yep. That’s why I said to use the home patrol command in utils.go, it calculates the checksum.

**Comment by rabarar** [comment]
talking directly to the serial port - not in go - 

so if I send the string “AUF\tSYS\t488” where 488 is the checksum of “AUF\tSYS\t” then I get back a valid response:

AUF		STS		ON		654

**Comment by rabarar** [comment]
#include <stdio.h>
#include <string.h>

unsigned int checksum(char *str);

int main(int argc, char *argv[]) {

    if (argc > 1) {
        checksum(argv[1]);
    }

}

unsigned int checksum(char *str) {
    int cs = 0;

    for (int i=0; i<strlen(str); i++) {
        cs += str[i];
    }
    printf("%s: sum = %u\n", str, cs);

    return cs;
}

so here’s a quick c program to compute checksums - I send commands to the SERIAL port and they work as you’d expect. But sending the same string to the UDP Port doesn’t result in a response.

**Comment by robbiet480** [comment]
Keep running through the commands I gave. If you get a data blob back, then we know it works and there’s just something off in the AUF parsing code for the SDS200.

**Comment by robbiet480** [comment]
Good distinction. So if you send via UDP you just get ERR? It may be formatting differences with tabs?

**Comment by rabarar** [comment]
no -  i’m not getting data with the sequence… grr


“AUF”, “STS” // returns ON/OFF for audio feed status
“AUF”, “STS”, “ON” // turn on audio feed
// wait for a audio transmission to complete
“AUF”, “INFO” // should show file name and size
“AUF”, “INFO”, “ACK” // ack that you have received file data
“AUF”, “DATA” // you’ll receive a data blob
“AUF”, “DATA”, “CAN” // cancel the data transfer

**Comment by rabarar** [comment]
I get no reply at all if I send via UDP - which is odd - i’d expect an ERR…

**Comment by robbiet480** [comment]
HomePatrol never supported WiFi (as far as I know) so I guess it's not too surprising. Seems like a oversight to not enable commands to work the same on both transports, but then again, leaving HomePatrol commands in at all is probably an oversight on its own.

**Comment by rabarar** [comment]
yeah - who knows what it’s doing on SDS200 - you’re getting audio data back successfully with the SDS100?

**Comment by robbiet480** [comment]
Yep! Audio comes through very quickly and with no issues for me.

**Comment by rabarar** [comment]
lucky bastard! lol

**Comment by rabarar** [comment]
send me a log snippet of your successful session

**Comment by rabarar** [comment]
all you’re doing is starting the ./bearcatter -u /dev/tty.usb… yes?

**Comment by robbiet480** [comment]
Send me a iMessage and let's continue this further. Can screen share. My address is me@robbiet.us.

**Pull request merged**
